version: "3.8"

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: verdaccio
    ports:
      - "4873:4873"
    volumes:
      - ~/verdaccio/storage:/verdaccio/storage
      - ~/verdaccio/config:/verdaccio/conf
    user: "${UID}:${GID}"   # 用你的帳號UID:GID來跑，避免 root 權限問題
    restart: always

volumes:
  verdaccio-storage:
  verdaccio-config:
